ubicacion:
  id: "ubicacion"
  titulo: "Visitanos en Escobar"
  direccion: "Ruta 25, km 3.5, Escobar, Buenos Aires"
  horario: "Lunes a sábados de 9 a 19 h. Domingos de 9 a 13 h."
  lat: -34.3486
  lng: -58.7969
